name:                pamela
version:             0.1.0
github:              "normenmueller/pamela"
license:             BSD3
author:              "Normen Müller"
maintainer:          "normen.mueller@gmail.com"
copyright:           "(c) 2023 Normen Müller"

extra-source-files:
- README.md
- HISTORY.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Simple

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/normenmueller/pamela#readme>

dependencies:
  - base >= 4.7 && < 5
  - optparse-applicative == 0.17.0.0
  - semver == 0.4.0.1

library:
  source-dirs: src

executables:
  pamela-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    # cf. https://github.com/commercialhaskell/stack/issues/5439
    when:
      - condition: false
        other-modules: Paths_pamela
    dependencies:
    - pamela

tests:
  pamela-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - pamela
