name:                pamela
version:             0.1.0
github:              "normenmueller/pamela"
license:             BSD3
author:              "Normen Müller"
maintainer:          "normen.mueller@gmail.com"
copyright:           "Copyright: (c) 2020 Normen Müller"

extra-source-files:
- README.md
- HISTORY.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Simple

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/normenmueller/pamela#readme>

dependencies:
  - base >= 4.7 && < 5
  - containers >= 0.6.0.1
  - directory >= 1.3.3.0
  - filepath >= 1.4.2.1
  - fgl >= 5.7.0.2
  - mtl >= 2.2.2
  - reducers >= 3.12.3
  - split >= 0.2.3.3
  - temporary >= 1.3
  - text >= 1.2.3.1
  - transformers >= 0.5.6.2
  - typed-process >= 0.2.6.0
  - xml-conduit >= 1.8.0.1
  - xml-types >= 0.3.6

library:
  source-dirs: src
  exposed-modules:
    - XML
    - AMX
    - Graph
    - Utils

executables:
  pamela-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - pamela

tests:
  pamela-test:
    main:                Spec.hs
    source-dirs:         tst
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - pamela
    - hspec
    - QuickCheck
    - MissingH
